apacblocks/registration

.gitignore, client/main.html, client/main.js, imports/startup/client/routes.js, imports/ui/App.js, imports/ui/pages/Join.js, imports/ui/pages/Login.js, imports/ui/pages/Notfound.js, imports/ui/pages/Register.js, package-lock.json, package.json, server/main.js, tests/main.js
Solution: provide a starting point for the project
=> Problem: no starting point

client/main.js
Solution: remove the line which has bug
=> Problem: error on startup

client/main.html, imports/api/account.js, imports/startup/client/routes.js, imports/ui/pages/Join.js, imports/ui/pages/Login.js, imports/ui/pages/Profile.js, imports/ui/pages/Register.js, package-lock.json, package.json, server/main.js
Solution: implement login &sign up with QR code
=> Problem: login& sign up is not implemented yet

server/main.js
solution: only allow users to create account if they have been invited by an existing user. Limit users to invite only 2 new users.
=> problem: users can created account without invite

imports/ui/pages/Login.js, imports/ui/pages/Profile.js, imports/ui/pages/Register.js
Solution: use BTC address as user name
=> Problem: using username is not good

imports/ui/pages/Register.js, imports/ui/pages/UserList.js
Solution: add sponsor name in user profile and userlist
=> Problem: not showing sponsor name

imports/ui/pages/Join.js, imports/ui/pages/Profile.js, imports/ui/pages/Register.js, imports/ui/pages/UserList.js
Solution: add a Bio section when register
=> Problem: no Bio

imports/ui/pages/Login.js, imports/ui/pages/Profile.js
Solution: change the '/' sign to 'or'
=> Problem: login screen / sign should change to 'or'

imports/ui/pages/Profile.js, imports/ui/pages/UserList.js
Solution: change it to be blocks
=> Problem: 'apac block' should be 'apac blocks'

imports/ui/pages/Register.js
Solution: redirect user when they manually connect to register
=> Problem: user can go to register manually

imports/ui/pages/Join.js, imports/ui/pages/Login.js, imports/ui/pages/Notfound.js, imports/ui/pages/Profile.js, imports/ui/pages/Register.js, imports/ui/pages/Shared/BottomNav.js, imports/ui/pages/Shared/TopNav.js, imports/ui/pages/UserList.js, imports/ui/pages/Welcome.js, package-lock.json, package.json, server/main.js
Solution:
- Moved header to shared component refactored existing components
- Refactored the footer adding Bottom Nav & moved to a shared component
- Better user experience expected when adding additional components
=> Problem: No shared component for top & bottom nav

client/main.js, imports/api/account.js, imports/startup/client/routes.js, imports/ui/App.js, imports/ui/pages/Join.js, imports/ui/pages/Login.js, imports/ui/pages/Notfound.js, imports/ui/pages/Profile.js, imports/ui/pages/Register.js, imports/ui/pages/Settings.js, imports/ui/pages/Shared/BottomNav.js, imports/ui/pages/Shared/SnackbarWrapper.js, imports/ui/pages/Shared/TopNav.js, imports/ui/pages/UserList.js, imports/ui/pages/Welcome.js, package-lock.json, package.json
Solution:
- Allowing users to edit bio, btcAddress and telegram link
- fixes #40
- fixes #32
=> problem: users can't edit their information #32

imports/api/account.js
Solution: Individually updating each attribute
=> Problem: Updating user replaces profile doc #43

imports/ui/pages/UserList.js
soluton: applied margin of 80px to container. fixes #46
=> problem: last member in user list is not seen #46

imports/ui/pages/Shared/BottomNav.js
Solution: default maxWidth value updated with 'none'
=>  Problem: Bottom nav buttons not aligned #39

.meteor/packages, .meteor/versions, imports/api/topics/methods.js, imports/api/topics/server/publications.js, imports/api/topics/topics.js, imports/startup/client/routes.js, imports/ui/pages/Settings.js, imports/ui/pages/Shared/BottomNav.js, imports/ui/pages/Topics.js, imports/ui/pages/Topics/ProposeTopic.js, package-lock.json, package.json, server/main.js
Solution:
- Added ability for members to create new presentation topics
- Created Topics page allowinng members to view all proposed topics
=> problem: members cannot propose a presentation #35

imports/startup/client/routes.js, imports/ui/pages/UserList.js, imports/ui/pages/Users/ViewProfile.js, package-lock.json, package.json, server/main.js
Solution:
- Modified user list view
- Add a user's profile page
- fixes #33
=> Problem: can't view other user's profiles #33

imports/ui/pages/Topics/ProposeTopic.js
Solution: Showing characters left under Topic form inputs. fixes #51
=> Problem: Char count not shown in topic form #51

imports/ui/helpers/index.js, imports/ui/pages/UserList.js, imports/ui/pages/Users/ViewProfile.js, server/main.js
Solution:
- Created helper function number of invites left for each user.
- fixes #34
=> Problem: Can't see who has remaining invites #34

imports/api/topics/server/publications.js, imports/startup/client/routes.js, imports/ui/pages/Login.js, imports/ui/pages/Settings.js, imports/ui/pages/Topics.js, imports/ui/pages/Topics/ProposeTopic.js, imports/ui/pages/Topics/ViewTopic.js, imports/ui/pages/Users/ViewProfile.js
Solution:
- Added a view topic page
- Redirected users when topic card is clicked
- improved login UI
- fixes #56
=> Problem: Members cannot view Topic details #56

imports/ui/constants/index.js, imports/ui/helpers/index.js
Solution:
- Subtracting total user invite count from maxnumber of allowed invites
- fixes #58
=> Problem: remaining invites is not accurate #58

imports/ui/pages/UserList.js, imports/ui/pages/Users/ViewProfile.js
solution: change from invite to remaining invites
=> problem: remaining invite terminology not clear

imports/ui/pages/Shared/TopNav.js, imports/ui/pages/Welcome.js
Solution: Change the userlist button back to the correct format
=> Problem: Save button disappear

imports/ui/pages/Users/ViewProfile.js
Solution: Access user from props
=> Problem: Reference Error thrown for user

imports/ui/pages/Join.js
=> Problem: join up page is broken #67
